// Acciones.js
const Acciones = {
    SALDO: "SALDO",
    MOVIMIENTOS: "MOVIMIENTOS",
    PRESTAMO: "PRESTAMO",
    RESUMEN: "RESUMEN",
    OPERADOR: "OPERADOR",
    PROMOS: "PROMOS",
    PAGAR: "PAGAR",
    SOLICITAR: "SOLICITAR",
    REQUISITOS: "REQUISITOS",
    NOCLIENTE: "MENU_NO_CLIENTE",
    VINCULAR: "NUEVO_CLIENTE_REGISTRADO",
    HOME: "MENU_PRINCIPAL"
};

export default Acciones;
